# Generated by Django 2.1.15 on 2020-02-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothmodel',
            name='cloth_img',
        ),
    ]
