# Generated by Django 2.1.15 on 2020-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_remove_clothmodel_cloth_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothmodel',
            name='cloth_img',
            field=models.ImageField(default='cloth_img/default.png', upload_to='cloth_img'),
        ),
        migrations.AddField(
            model_name='clothmodel',
            name='cloth_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clothmodel',
            name='cloth_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
